# Generated by Django 2.2.5 on 2019-11-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191103_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(help_text='Date of birth', null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('wont-say', "Won't say")], default='wont-say', help_text="User's gender", max_length=30, null=True, verbose_name='Gender'),
        ),
    ]
