# Generated by Django 2.2.5 on 2019-11-17 14:19

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191109_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=users.models.user_profile_directory_path, verbose_name='Profile Picture'),
        ),
    ]
