# Generated by Django 2.2.5 on 2019-11-17 14:42

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_profile_directory_path, verbose_name='Profile Picture'),
        ),
    ]
