# Generated by Django 2.2.5 on 2019-11-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='num_seats',
            field=models.IntegerField(default=1, help_text='Number of seats available', verbose_name='Number of seats'),
        ),
    ]
